### ISSUE TITLE
Experiencing hangs with Intel-MLSL and ResNet-50 multi-node training

### ISSUE THREAD

**Issue by awan-10** [intel/caffe#112]
Hi folks,

I am getting a hang when I run multi-node training using Intel-Caffe and Intel-MLSL. 

I am at this particular commit for Intel-Caffe:

commit b0ef3236528a2c7d2988f249d347d5fdae831236
Author: Haihao Shen <haihao.shen@intel.com>
Date:   Wed May 17 11:19:56 2017 +0800

    Upgrade MKL-DNN to version ecf1883a94239a19d442356d32e1076a15b88e7a

I am using Intel-MLSL mlsl_2017.0.014.

**This is the run command:**

mpirun -n 4 -ppn 1 -hostfile hosts -IB -genv I_MPI_OFA_ADAPTER_NAME mlx5_0 
-env GLOG_log_dir $PWD/log ./build/tools/caffe train -solver models/default_resnet_50/solver.prototxt -engine MKL2017

**This is the output from the program where I am stuck:**

```bash
Thread 4 (Thread 0x7f3d3effb480 (LWP 29419)):
#0  0x00007f3ea57ae6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib64/libpthread.so.0
#1  0x00007f3ea5f8c3ef in __kmp_suspend_64 () from /home/awan/projects/intel-apr17-caffe-mlsl/./external/mkl/mklml_lnx_2018.0.20170425//lib/libiomp5.so
#2  0x00007f3ea5f2c95c in _INTERNAL_25_______src_kmp_barrier_cpp_1d20fae8::__kmp_hyper_barrier_release(barrier_type, kmp_info*, int, int, int, void*) () from /home/awan/projects/intel-apr17-caffe-mlsl/./external/mkl/mklml_lnx_2018.0.20170425//lib/libiomp5.so
#3  0x00007f3ea5f2e1d8 in __kmp_fork_barrier(int, int) () from /home/awan/projects/intel-apr17-caffe-mlsl/./external/mkl/mklml_lnx_2018.0.20170425//lib/libiomp5.so
#4  0x00007f3ea5f57110 in __kmp_launch_thread () from /home/awan/projects/intel-apr17-caffe-mlsl/./external/mkl/mklml_lnx_2018.0.20170425//lib/libiomp5.so
#5  0x00007f3ea5f88193 in _INTERNAL_24_______src_z_Linux_util_c_3e0095e6::__kmp_launch_worker(void*) () from /home/awan/projects/intel-apr17-caffe-mlsl/./external/mkl/mklml_lnx_2018.0.20170425//lib/libiomp5.so
#6  0x00007f3ea57aadc5 in start_thread () from /usr/lib64/libpthread.so.0
#7  0x00007f3ea54d976d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7f3d3ebfa700 (LWP 29420)):
#0  0x00007f3ea57ae6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib64/libpthread.so.0
#1  0x00007f3eab6c4f5b in boost::condition_variable::wait(boost::unique_lock<boost::mutex>&) () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#2  0x00007f3eab6c5708 in caffe::BlockingQueue<std::string*>::pop(std::string const&) () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#3  0x00007f3eab4db306 in caffe::DataReader::Body::read_one(caffe::DataReader::DBWrapper*, caffe::DataReader::QueuePair*) () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#4  0x00007f3eab4dbdf4 in caffe::DataReader::Body::InternalThreadEntry() () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#5  0x00007f3ea6593df4 in thread_proxy () from /opt/boost/1.58.0/lib/libboost_thread.so.1.58.0
#6  0x00007f3ea57aadc5 in start_thread () from /usr/lib64/libpthread.so.0
#7  0x00007f3ea54d976d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7f3d15769700 (LWP 29421)):
#0  0x00007f3ea57ae6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib64/libpthread.so.0
#1  0x00007f3eab6c4f5b in boost::condition_variable::wait(boost::unique_lock<boost::mutex>&) () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#2  0x00007f3eab6c5708 in caffe::BlockingQueue<std::string*>::pop(std::string const&) () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#3  0x00007f3eab4db306 in caffe::DataReader::Body::read_one(caffe::DataReader::DBWrapper*, caffe::DataReader::QueuePair*) () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#4  0x00007f3eab4dbdf4 in caffe::DataReader::Body::InternalThreadEntry() () from /home/awan/projects/intel-apr17-caffe-mlsl/.build_release/tools/../lib/libcaffe.so.1.0.0-rc3
#5  0x00007f3ea6593df4 in thread_proxy () from /opt/boost/1.58.0/lib/libboost_thread.so.1.58.0
#6  0x00007f3ea57aadc5 in start_thread () from /usr/lib64/libpthread.so.0
#7  0x00007f3ea54d976d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7f3eb3cf9800 (LWP 29376)):
#0  0x00007f3eab02ce40 in cqueue_wait () from /home/awan/intel/mlsl_2017.0.014/intel64/lib/libmlsl.so.1
#1  0x00007f3eab04bf7c in MLSL::CommRequest::Wait(bool) () from /home/awan/intel/mlsl_2017.0.014/intel64/lib/libmlsl.so.1
#2  0x00007f3eab03ab86 in MLSL::Environment::Wait(int*) () from /home/awan/intel/mlsl_2017.0.014/intel64/lib/libmlsl.so.1
#3  0x00007f3eb3d62e2e in caffe::MultiSync<float>::run() ()
#4  0x00007f3eb3d59fc1 in train() ()
#5  0x00007f3eb3d539bc in main ()
```
**This is the process stack:**

```bash
I0829 17:15:25.915491 29376 net.cpp:346] data does not need backward computation.
I0829 17:15:25.915493 29376 net.cpp:388] This network produces output label
I0829 17:15:25.915496 29376 net.cpp:388] This network produces output probt
I0829 17:15:25.915586 29376 net.cpp:424] Network initialization done.
I0829 17:15:25.916523 29376 solver.cpp:119] Solver scaffolding done.
I0829 17:15:25.916888 29376 caffe.cpp:319] Configuring multinode setup
I0829 17:15:25.916935 29376 caffe.cpp:321] Starting Multi-node Optimization in MLSL environment
W0829 17:15:25.916939 29376 multi_sync.hpp:124] RUN: PER LAYER TIMINGS ARE DISABLED, SINGLE DB SPLITTING IS DISABLED
W0829 17:15:25.916954 29376 multi_sync.hpp:116] synchronize_params: bcast
```

**Comment by awan-10** [comment]
This issue can be resolved by updating the repo to the latest commit.  Thank you, folks, for fixing the hangs in the latest version. I am closing this issue.
