### ISSUE TITLE
Problems of pycaffe (environment of 4.13.0-38-generic #43~16.04.1-Ubuntu)

### ISSUE THREAD

**Issue by lddsdu** [intel/caffe#196]
when I compiled the python interface of caffe,it passed successfully. but when I import caffe in python console,it went wrong like that:

\>\>\> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/__init__.py", line 37, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 49, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libmlsl.so.1: cannot open shared object file: No such file or directory

Then I execute the command below.
~/caffe/python$ ldd caffe/_caffe.so 
        linux-vdso.so.1 =>  (0x00007ffd405be000)
	libcaffe.so.1.1.0 => /home/intel/caffe/python/caffe/../../build/lib/libcaffe.so.1.1.0 (0x00007f2d3931b000)
	**libmlsl.so.1 => not found**
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f2d390ec000)
	libprotobuf.so.9 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.9 (0x00007f2d38dce000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2d38a4c000)
	libboost_python-py27.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0 (0x00007f2d38800000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f2d38272000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2d3805c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2d37c92000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f2d37a8e000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f2d37876000)
	libboost_regex.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0 (0x00007f2d3756e000)
	libmklml_intel.so => /home/intel/caffe/./external/mkl/mklml_lnx_2018.0.1.20171227//lib/libmklml_intel.so (0x00007f2d2e72b000)
	**libmlsl.so.1 => /home/intel/caffe/./external/mlsl/l_mlsl_2018.0.003//intel64/lib/libmlsl.so.1 (0x00007f2d2e497000)**
	libmkldnn.so.0 => /home/intel/caffe/external/mkldnn/install/lib/libmkldnn.so.0 (0x00007f2d2dd83000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007f2d2db62000)
        ......

here are two Dynamic link library named libmlsl.so.1 need to be linked, but one can not find, I do not have so much knowledge of c++ and I want to know what is going wrong.

**Comment by fzou1** [comment]
Thank you for your suggestion. We'll look into it.

**Comment by PyNancy** [comment]
hi ,i meet the question :"ImportError: libglog.so.0: cannot open shared object file: No such file or directory",can i use you method to solve it ?

**Comment by ftian1** [comment]
@PyNancy 
run "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/" if you can find libglog.so under this folder.
